### PR TITLE
Add support for grouped time series

### PR DESCRIPTION
**Pull request by noahsa**
Added the capability to create a grouped time series summing matrix. The methodology takes a slightly different string-based approach to build the summing matrix by string searching the node's keys within the tree, based on the assumption that nodes keys are delimited by underscores(could be any character) and the levels in the hierarchy are unique. I would love your feedback or any further discussion.

If this is a duplicate or already possible in the library, please let me know and I'd be happy to update the documentation to help others like myself with some guidance.

I have included unit tests.

I have not updated the documentation, since it will need to be updated in a couple of places/ examples. Although, I am happy to make the updates based on feedback.

### CODE REVIEW

**Comment by carlomazzaferro** [comment]
Sorry for the late one, but this looks really good to me. Thanks for taking the time! I'll approve for now, but I'd like to get the documentation updated in the time being. Would you be open to that?

**Review by carlomazzaferro — APPROVED** [review]

**Comment by noahsa** [comment]
Yes, I'd be happy to! I'll work on that this week.

**Comment by noahsa** [comment]
All documentation/ unit tests are updated.

Two additional change made:
1. Returned the labels associated with the rows of the summing matrix from to_sum_mat as well.
2. Added an example to the docs of OLS optimal reconciliation using forecasts created outside scikit-hts.

I did not update HISTORY.rst, since it looks to be tied to bumping the version. I'm new to this, so I was not if I should do this.

Please let me know if there is anything else I should do.

**Comment by carlomazzaferro** [comment]
This is outstanding work, documentation also looks good to me. The only thing I'm slightly worried is the case in which people have other columns with underscores -- but the documentation makes it clear enough what the structure should be. Merging in! Thanks for working on this

**Comment by noahsa** [comment]
Thank you! I agree, the underscore constraint is bit worrisome. It would be fairly easy to allow the user to specify a delimiter other than underscore, but more thought would need to go into eliminating the need for a delimiter all together in a future PR.

**Pull request merged**
