### PR TITLE
Bu bugfix incorrect keys

### PR DESCRIPTION
**Pull request by javierhuertay**
fixing black and isort formatting

### CODE REVIEW

**Comment by carlomazzaferro** [comment]
https://github.com/carlomazzaferro/scikit-hts/issues/35#issuecomment-821781040 Posting here for visibillity @javierhuertay let me know if something is unclear

**Comment by javierhuertay** [comment]
> 
> 
> [#35 (comment)](https://github.com/carlomazzaferro/scikit-hts/issues/35#issuecomment-821781040) Posting here for visibillity @javierhuertay let me know if something is unclear

The library seems to be having some fails in the tests,
as can be seen here.
image
I'm working with the latest commit, and it throw 2 errors.

If i edit revision.py it throws the same ones, as can be seen here.
image
i don't what else to do to solve this.

The sintaxis in isort changed, as no version is defined in the req i used the last one , to black --check . && **isort --check -p black  *.py**

image
That seems to be fine.

**Comment by carlomazzaferro** [comment]
Want to jump on slack? https://join.slack.com/t/scikit-hts/shared_invite/zt-d5is54bp-iOeagm7Jv68ZTkjk_zezrA We can chat there

**Comment by carlomazzaferro** [comment]
FWIW, I've just realised that some dependencies might have gotten out of sync -- I've thus updated the dependencies, as well as the CONTRIBUTING guide. There you can find the latest steps to get all the dev dependencies installed, as well as the ones required for testing.

See: https://github.com/carlomazzaferro/scikit-hts/blob/master/CONTRIBUTING.rst#get-started

The main difference is that I've added the pinned versions of black, flake8, and isort to the dev deps, as well as pinned version of pystan. This is because pystan>3.0 breaks fbprophet.

Let me know how this goes!

**Pull request closed without merging**
